name: CI/CD Pipeline   

on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        
      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .


      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying to PRODUCTION..."
