name: CI/CD Pipeline   

on:
    push:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Install dependencies
        run: npm install
        
      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .


      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying to PRODUCTION..."
